apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "application.fullname" . }}
  labels:
    app: {{ template "application.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "application.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "application.name" . }}
    spec:
      containers:
        - name: {{ template "application.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
