apiVersion: v1
kind: Service
metadata:
  name: {{ template "application.fullname" . }}
  labels:
    app: {{ template "application.name" . }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
  selector:
    app: {{ template "application.name" . }}
